### ISSUE TITLE
reCAPTCHA error. Invalid domain for site key.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/reCAPTCHA#3]
I entereg correct API keys and added site url reCAPTCHA admin panel.
If i enabled reCAPTCHA phpfox admin panel im getting "Invalid domain for site key." error.

**Comment by RaymondBenc** [comment]
I noticed another you issue had with passing data over HTTP(s). Do you know if your server is blocking external calls to web apis?

**Comment by Ylmzef** [comment]
I think no.

**Comment by Ylmzef** [comment]
Im still waiting for this issue can you help me please?

**Comment by RaymondBenc** [comment]
Since we cannot reproduce this on our community, nor can we reproduce it locally, you need to get in [touch with us](http://www.phpfox.com/contact/) and provide us with your sites URL and AdminCP login details.

**Comment by Ylmzef** [comment]
Its now fixed after i recreate app and update api keys.
It was old api key for recaptcha v1.
