### ISSUE TITLE
No recaptha /user/register/

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/reCAPTCHA#4]
There no recaptha box in /user/register/ page!!!

**Comment by RaymondBenc** [comment]
Issue fixed in v1.1 of this app https://github.com/moxi9/reCAPTCHA/commit/69c6ed367c342a0d58b3f0719253204c510bc021

After upgrading the app make sure to clear your sites cache.

**Comment by Ylmzef** [comment]
How can i update a app?
There no upgrade button in admincp.
